
import { Car, Review } from './types';

export const MOCK_CARS: Car[] = [];

export const MOCK_REVIEWS: Review[] = [
  {
    id: '1',
    name: 'Andrei Popescu',
    carPurchased: 'BMW X5 M50d',
    rating: 5,
    comment: 'Servicii impecabile. Mașina a fost exact ca în descriere, iar procesul de cumpărare a durat mai puțin de o oră.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop'
  },
  {
    id: '2',
    name: 'Elena Ionescu',
    carPurchased: 'Porsche Macan',
    rating: 5,
    comment: 'Profesionalism și transparență totală. Recomand Autoparc RolCris pentru oricine caută o mașină premium verificată.',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=200&auto=format&fit=crop'
  },
  {
    id: '3',
    name: 'Mihai Radu',
    carPurchased: 'Mercedes E-Class',
    rating: 5,
    comment: 'O experiență de 5 stele. Echipa a fost foarte răbdătoare și m-a ajutat să aleg configurația perfectă pentru mine.',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop'
  }
];

export const BRANDS = ['BMW', 'Mercedes-Benz', 'Porsche', 'Audi', 'Tesla', 'Land Rover', 'Jaguar', 'Volvo', 'Skoda', 'Dacia', 'Volkswagen', 'Toyota', 'Ford', 'Renault'];
export const BODY_TYPES = ['SUV', 'Sedan', 'Coupe', 'Cabrio', 'Break', 'Hatchback'];
export const FUELS = ['Diesel', 'Benzină', 'Hibrid', 'Electric'];

export const CAR_FEATURES = [
  "7 Locuri",
  "Bord digital",
  "Computer de bord",
  "Inchidere centralizata",
  "Keyless Go",
  "Keyless Entry",
  "Servodirectie",
  "ABS",
  "ASR",
  "Asistenta in panta",
  "Asistenta in rampa",
  "Controlul stabilitatii (ESP)",
  "Cutie manuala",
  "6 Viteze",
  "Cutie automata",
  "Functie Start/Stop",
  "Tractiune (4x4)",
  "Tractiune (4X4) automat",
  "Avertizare unghi mort",
  "Lane Assist",
  "Front Assist",
  "Sistem recunoastere indicatoare rutiere",
  "Apple Carplay",
  "Android Auto",
  "Conexiune internet",
  "Bluetooth",
  "Radio",
  "CD Player",
  "Sistem audio",
  "USB/AUX",
  "Wireless Charging",
  "Navigatie GPS",
  "Ecran color cu Touch Screen",
  "Head up display",
  "Senzori parcare fata",
  "Senzori parcare spate",
  "Sistem de parcare automat",
  "Camera video 360º",
  "Camera marsarier",
  "Airbag-uri frontale",
  "Airbag-uri laterale",
  "Aer conditionat",
  "Aer conditionat automat",
  "Aer conditionat automat/in 2 zone",
  "Aer conditionat automat/in 3 zone",
  "Aer conditionat automat/in 4 zone",
  "Volan reglabil imbracat in piele",
  "Volan reglabil electric",
  "Comenzi volan",
  "Padele volan",
  "Interior piele",
  "Interior Piele/Mixt",
  "Incalzire in scaune fata",
  "Incalzire in scaune spate",
  "Scaun sofer electric",
  "Scaun pasager electric",
  "Scaun sofer electric cu memorie",
  "Scaun pasager electric cu memorie",
  "Suport lombar electric scaun sofer",
  "Suport lombar electric scaun pasager",
  "Senzor ploaie",
  "Stergatoare automate",
  "Lumini automate",
  "Faruri Xenon",
  "Faruri Bi-Xenon",
  "Spalator faruri",
  "Lumini de zi",
  "Lumini de zi LED",
  "Faruri ceata",
  "Stopuri LED",
  "Lumini ambientale",
  "Trapa electrica",
  "Plafon panoramic",
  "Oglinzi exterioare electrice cu incalzire",
  "Oglinzi exterioare rabatabile electric",
  "Geamuri Fata/Spate electrice",
  "Geamuri laterale spate fumurii",
  "Luneta fumurie",
  "Luneta cu incalzire",
  "Cotiera fata",
  "Cotiera Fata/Spate",
  "Cotiera spate cu suport pahar",
  "Portbagaj electric",
  "Senzor presiune roti",
  "Jante aliaj",
  "Carlig remorcare",
  "Carlig remorcare electric"
];
