
import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { ChevronLeft, Share2, Phone, MessageCircle, Check, Calendar, Gauge, Fuel, Zap, Settings, MapPin, Layout, CarFront, Fingerprint, Clock, X, CheckCircle, AlertTriangle } from 'lucide-react';
import { useCars } from '../context/CarContext';

const CarDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const { cars, addBooking } = useCars();
  const car = cars.find(c => c.id === id);
  const [activeImage, setActiveImage] = useState(0);
  const [isBookingOpen, setIsBookingOpen] = useState(false);

  // Booking Form State
  const [bookingDate, setBookingDate] = useState('');
  const [bookingTime, setBookingTime] = useState('');
  const [clientName, setClientName] = useState('');
  const [clientPhone, setClientPhone] = useState('');
  const [bookingSuccess, setBookingSuccess] = useState(false);

  // Scroll to top on mount
  useEffect(() => {
    window.scrollTo(0, 0);
  }, [id]);

  if (!car) return <div className="h-screen flex items-center justify-center text-gray-900 dark:text-white">Car not found</div>;

  const handleBookingSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!car) return;

    await addBooking({
      id: '', // Generated by Firebase
      carId: car.id,
      carName: `${car.make} ${car.model}`,
      carImage: car.images[0],
      customerName: clientName,
      customerPhone: clientPhone,
      date: `${bookingDate}T${bookingTime}`,
      status: 'pending',
      createdAt: Date.now(),
      type: 'Test Drive' // Explicitly set type
    });

    setBookingSuccess(true);
    setTimeout(() => {
      setBookingSuccess(false);
      setIsBookingOpen(false);
      // Reset form
      setClientName('');
      setClientPhone('');
      setBookingDate('');
      setBookingTime('');
    }, 2000);
  };

  const SpecItem = ({ icon: Icon, label, value }: { icon: any, label: string, value: string | number }) => (
    <div className="flex flex-col items-center justify-center p-4 bg-white dark:bg-white/5 rounded-xl border border-gray-200 dark:border-white/5 hover:border-gold-500/30 transition-colors group shadow-sm dark:shadow-none">
      <Icon className="text-gold-500 mb-2 group-hover:scale-110 transition-transform" size={24} />
      <span className="text-xs text-gray-500 uppercase tracking-wider mb-1">{label}</span>
      <span className="text-gray-900 dark:text-white font-semibold text-center">{value}</span>
    </div>
  );

  // Pre-filled WhatsApp Message
  const whatsappMessage = `Salut! Sunt interesat de ${car.make} ${car.model} (${car.year}) - ID: ${car.id}. Vă rog să îmi oferiți mai multe detalii.`;
  const whatsappLink = `https://wa.me/40740513713?text=${encodeURIComponent(whatsappMessage)}`;

  return (
    <div className="min-h-screen pt-24 pb-12 px-4 max-w-7xl mx-auto">
      
      {/* Breadcrumb & Navigation */}
      <div className="flex justify-between items-center mb-6">
        <Link to="/inventory" className="flex items-center gap-2 text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white transition-colors">
          <ChevronLeft size={20} />
          Înapoi la Stoc
        </Link>
        <button className="text-gray-500 dark:text-gray-400 hover:text-gold-500 transition-colors">
          <Share2 size={20} />
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-12">
        
        {/* Left Column: Visuals (7 cols) */}
        <div className="lg:col-span-7 space-y-4">
          <div className="relative aspect-[16/10] bg-gray-100 dark:bg-[#121212] rounded-2xl overflow-hidden shadow-2xl border border-gray-200 dark:border-white/5">
            <img 
              src={car.images[activeImage]} 
              alt={car.model} 
              referrerPolicy="no-referrer"
              className={`w-full h-full object-cover animate-fade-in ${car.isSold ? 'grayscale-[50%]' : ''}`}
            />
            {car.isSold ? (
               <div className="absolute inset-0 flex items-center justify-center bg-black/40 backdrop-blur-[2px]">
                  <div className="border-4 border-red-600 text-red-600 px-8 py-3 text-4xl font-black uppercase tracking-widest -rotate-12 bg-white/10 backdrop-blur-sm shadow-2xl">
                    VÂNDUT
                  </div>
               </div>
            ) : car.isHotDeal && (
              <div className="absolute top-6 left-6 bg-red-600 text-white px-4 py-2 rounded-full font-bold shadow-lg flex items-center gap-2">
                <Zap size={16} fill="currentColor" /> HOT DEAL
              </div>
            )}
          </div>
          
          <div className="grid grid-cols-4 gap-4">
            {car.images.map((img, idx) => (
              <button 
                key={idx}
                onClick={() => setActiveImage(idx)}
                className={`aspect-[16/10] rounded-lg overflow-hidden border-2 transition-all ${activeImage === idx ? 'border-gold-500 opacity-100' : 'border-transparent opacity-60 hover:opacity-100'}`}
              >
                <img src={img} alt="thumbnail" className="w-full h-full object-cover" referrerPolicy="no-referrer" />
              </button>
            ))}
          </div>

          <div className="glass-panel p-8 rounded-2xl mt-8 bg-white dark:bg-[#121212]/50 border border-gray-200 dark:border-white/10">
            <h3 className="text-xl font-display font-bold text-gray-900 dark:text-white mb-4">Descriere</h3>
            <p className="text-gray-600 dark:text-gray-300 leading-relaxed whitespace-pre-line">{car.description}</p>
          </div>
        </div>

        {/* Right Column: Details & CTA (5 cols) */}
        <div className="lg:col-span-5">
          <div className="sticky top-28 space-y-6">
            
            {/* Header Info */}
            <div>
              <h1 className="text-4xl md:text-5xl font-display font-bold text-gray-900 dark:text-white mb-6">{car.make} {car.model}</h1>
              
              <div className="text-5xl font-display font-bold text-gray-900 dark:text-white mb-2">
                {car.isSold ? (
                  <span className="text-red-500">VÂNDUT</span>
                ) : (
                  <>
                    {car.price.toLocaleString()} <span className="text-gold-500">€</span>
                  </>
                )}
              </div>
              {!car.isSold && <p className="text-sm text-gray-500">Finanțare disponibilă</p>}
            </div>

            {/* CTA Box */}
            <div className="glass-panel p-6 rounded-2xl border-gold-500/20 shadow-[0_0_40px_rgba(197,160,89,0.05)] bg-white dark:bg-[#121212]/80">
               {car.isSold ? (
                 <div className="text-center py-4 bg-red-500/10 border border-red-500/20 rounded-xl">
                    <p className="text-red-500 font-bold flex items-center justify-center gap-2">
                       <AlertTriangle size={20} />
                       Acest autoturism nu mai este disponibil.
                    </p>
                    <Link to="/inventory" className="text-sm text-gray-500 underline mt-2 block hover:text-gray-900 dark:hover:text-white">
                       Vezi alte oferte similare
                    </Link>
                 </div>
               ) : (
                 <>
                   <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                      <a 
                        href={whatsappLink} 
                        target="_blank" 
                        rel="noreferrer"
                        className="flex items-center justify-center gap-2 bg-[#25D366] hover:bg-[#20bd5a] text-white py-4 rounded-xl font-bold transition-transform hover:scale-[1.02]"
                      >
                        <MessageCircle size={20} />
                        WhatsApp
                      </a>
                      <a 
                        href="tel:+40740513713" 
                        className="flex items-center justify-center gap-2 bg-transparent border-2 border-gray-900 dark:border-white hover:bg-gray-900 dark:hover:bg-white hover:text-white dark:hover:text-black text-gray-900 dark:text-white py-4 rounded-xl font-bold transition-all"
                      >
                        <Phone size={20} />
                        Sună Acum
                      </a>
                   </div>
                   
                   <button 
                      onClick={() => setIsBookingOpen(true)}
                      className="w-full bg-gold-500 hover:bg-gold-600 text-black font-bold py-4 rounded-xl transition-transform hover:scale-[1.02] flex items-center justify-center gap-2 shadow-lg shadow-gold-500/20"
                   >
                     <Calendar size={20} />
                     Programează Test Drive
                   </button>

                   <p className="text-center text-xs text-gray-500 mt-4">Răspundem de obicei în &lt; 15 minute</p>
                 </>
               )}
            </div>

            {/* Quick Specs */}
            <div className="grid grid-cols-2 gap-4">
              <SpecItem icon={Calendar} label="An" value={car.year} />
              <SpecItem icon={Gauge} label="Rulaj" value={`${car.mileage.toLocaleString()} km`} />
              <SpecItem icon={Fuel} label="Combustibil" value={car.fuel} />
              <SpecItem icon={Settings} label="Cutie Viteze" value={car.transmission} />
              <SpecItem icon={CarFront} label="Caroserie" value={car.bodyType} />
              <SpecItem icon={Zap} label="Motorizare" value={`${car.engineSize} • ${car.power} CP`} />
              <SpecItem icon={Fingerprint} label="VIN" value={car.vin || 'Nespecificat'} />
            </div>

            {/* Features Table */}
            <div className="glass-panel p-6 rounded-2xl bg-white dark:bg-[#121212]/50 border border-gray-200 dark:border-white/10">
              <h3 className="text-lg font-bold text-gray-900 dark:text-white mb-4">Dotări Principale</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-3">
                {car.features.map((feature, idx) => (
                  <div key={idx} className="flex items-start gap-3 text-gray-600 dark:text-gray-300">
                    <div className="mt-1 w-4 h-4 rounded-full bg-gold-500/20 flex items-center justify-center shrink-0">
                      <Check size={10} className="text-gold-500" />
                    </div>
                    <span className="text-sm">{feature}</span>
                  </div>
                ))}
              </div>
            </div>

          </div>
        </div>
      </div>

      {/* Booking Modal */}
      {isBookingOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-fade-in">
          <div className="bg-white dark:bg-[#121212] w-full max-w-md rounded-2xl border border-gray-200 dark:border-white/10 flex flex-col shadow-2xl relative overflow-hidden">
             
             {/* Header */}
             <div className="p-6 border-b border-gray-200 dark:border-white/10 bg-gray-50 dark:bg-white/5 flex justify-between items-center">
                <h3 className="text-xl font-display font-bold text-gray-900 dark:text-white">Programează Vizionare</h3>
                <button onClick={() => setIsBookingOpen(false)} className="text-gray-500 hover:text-red-500 transition-colors">
                  <X size={24} />
                </button>
             </div>

             {/* Form Content */}
             <div className="p-6">
               {bookingSuccess ? (
                 <div className="text-center py-8">
                   <div className="w-20 h-20 bg-green-500/10 rounded-full flex items-center justify-center text-green-500 mx-auto mb-4">
                     <Check size={40} />
                   </div>
                   <h4 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">Cerere Trimisă!</h4>
                   <p className="text-gray-500 text-sm">Te vom contacta în curând pentru confirmarea orei.</p>
                 </div>
               ) : (
                 <form onSubmit={handleBookingSubmit} className="space-y-4">
                    <div>
                      <label className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1 block">Numele Tău</label>
                      <input 
                        type="text" 
                        required
                        value={clientName}
                        onChange={(e) => setClientName(e.target.value)}
                        className="w-full bg-gray-50 dark:bg-white/5 border border-gray-200 dark:border-white/10 rounded-lg p-3 text-gray-900 dark:text-white outline-none focus:border-gold-500 transition-all"
                        placeholder="Ex: Ion Popescu"
                      />
                    </div>
                    
                    <div>
                      <label className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1 block">Telefon</label>
                      <input 
                        type="tel" 
                        required
                        value={clientPhone}
                        onChange={(e) => setClientPhone(e.target.value)}
                        className="w-full bg-gray-50 dark:bg-white/5 border border-gray-200 dark:border-white/10 rounded-lg p-3 text-gray-900 dark:text-white outline-none focus:border-gold-500 transition-all"
                        placeholder="Ex: 07xx xxx xxx"
                      />
                    </div>

                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <label className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1 block">Data Dorită</label>
                        <input 
                          type="date" 
                          required
                          min={new Date().toISOString().split('T')[0]}
                          value={bookingDate}
                          onChange={(e) => setBookingDate(e.target.value)}
                          className="w-full bg-gray-50 dark:bg-white/5 border border-gray-200 dark:border-white/10 rounded-lg p-3 text-gray-900 dark:text-white outline-none focus:border-gold-500 transition-all cursor-pointer"
                        />
                      </div>
                      <div>
                        <label className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1 block">Ora</label>
                        <select 
                          required
                          value={bookingTime}
                          onChange={(e) => setBookingTime(e.target.value)}
                          className="w-full bg-gray-50 dark:bg-white/5 border border-gray-200 dark:border-white/10 rounded-lg p-3 text-gray-900 dark:text-white outline-none focus:border-gold-500 transition-all cursor-pointer"
                        >
                          <option value="">Alege...</option>
                          <option value="09:00">09:00</option>
                          <option value="10:00">10:00</option>
                          <option value="11:00">11:00</option>
                          <option value="12:00">12:00</option>
                          <option value="13:00">13:00</option>
                          <option value="14:00">14:00</option>
                          <option value="15:00">15:00</option>
                          <option value="16:00">16:00</option>
                          <option value="17:00">17:00</option>
                        </select>
                      </div>
                    </div>

                    <div className="bg-gold-500/10 p-3 rounded-lg border border-gold-500/20 mt-4">
                      <p className="text-xs text-gold-500 flex items-center gap-2">
                        <CheckCircle size={14} /> Mașina: <span className="font-bold">{car.make} {car.model}</span>
                      </p>
                    </div>

                    <button type="submit" className="w-full bg-gold-500 hover:bg-gold-600 text-black font-bold py-3 rounded-xl mt-4 transition-all flex items-center justify-center gap-2">
                      Trimite Cererea
                    </button>
                 </form>
               )}
             </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default CarDetail;
