
import React, { useEffect, useState } from 'react';
import { MapPin, Phone, Mail, Clock, Send, MessageSquare, CheckCircle, ExternalLink } from 'lucide-react';
import { useCars } from '../context/CarContext';

const Contact: React.FC = () => {
  const { addMessage } = useCars();
  const [formState, setFormState] = useState({
    name: '',
    email: '',
    phone: '',
    message: ''
  });
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isSent, setIsSent] = useState(false);

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    
    try {
      await addMessage({
        id: '', // Generated by Firestore
        name: formState.name,
        email: formState.email,
        phone: formState.phone,
        message: formState.message,
        date: new Date().toISOString(),
        isRead: false
      });

      setIsSent(true);
      setFormState({ name: '', email: '', phone: '', message: '' });
      // Reset success message after 5 seconds
      setTimeout(() => setIsSent(false), 5000);
    } catch (error) {
      console.error("Error sending message:", error);
      alert("A apărut o eroare la trimiterea mesajului. Te rugăm să încerci din nou.");
    } finally {
      setIsSubmitting(false);
    }
  };

  const locations = [
    { 
      city: 'Satu Mare', 
      addr: 'B-dul Lucian Blaga 347', 
      tel: '0740 513 713', 
      mapQuery: 'Bulevardul+Lucian+Blaga+347,+Satu+Mare' 
    },
    { 
      city: 'Seini', 
      addr: 'Piața Unirii 2', 
      tel: '0745 123 456', 
      mapQuery: 'Piața+Unirii+2,+Seini' 
    },
    { 
      city: 'Tășnad', 
      addr: 'Str. N. Bălcescu 19', 
      tel: '0742 987 654', 
      mapQuery: 'Strada+Nicolae+Bălcescu+19,+Tășnad' 
    },
  ];

  return (
    <div className="w-full min-h-screen bg-gray-50 dark:bg-[#0a0a0a] pt-28 pb-12 px-4 transition-colors duration-300">
      
      {/* Header */}
      <div className="max-w-7xl mx-auto text-center mb-16">
        <h1 className="text-5xl md:text-6xl font-display font-bold text-gray-900 dark:text-white mb-6 animate-fade-in-up">
          Contactează <span className="text-gold-500">RolCris</span>
        </h1>
        <p className="text-gray-600 dark:text-gray-400 text-lg max-w-2xl mx-auto animate-fade-in-up delay-200">
          Suntem aici pentru a te ajuta să găsești mașina perfectă. Trimite-ne un mesaj sau vizitează-ne într-una dintre locațiile noastre.
        </p>
      </div>

      <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-12 mb-24">
        
        {/* Contact Form */}
        <div className="lg:col-span-7 animate-fade-in-left">
          <div className="glass-panel p-8 md:p-10 rounded-3xl bg-white dark:bg-[#121212] border border-gray-200 dark:border-white/10 shadow-xl relative overflow-hidden">
            
            {isSent ? (
              <div className="absolute inset-0 flex flex-col items-center justify-center bg-white/95 dark:bg-[#121212]/95 backdrop-blur-sm z-20 animate-fade-in">
                <div className="w-20 h-20 bg-green-500/10 rounded-full flex items-center justify-center text-green-500 mb-6">
                  <CheckCircle size={40} />
                </div>
                <h3 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">Mesaj Trimis!</h3>
                <p className="text-gray-500 text-center">Te vom contacta în cel mai scurt timp.</p>
                <button 
                  onClick={() => setIsSent(false)} 
                  className="mt-8 text-gold-500 hover:text-gold-600 font-bold"
                >
                  Trimite alt mesaj
                </button>
              </div>
            ) : null}

            <h3 className="text-2xl font-display font-bold text-gray-900 dark:text-white mb-8">Trimite un mesaj</h3>
            
            <form onSubmit={handleSubmit} className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-2">
                  <label className="text-xs font-bold text-gray-500 uppercase tracking-wider">Nume Complet</label>
                  <input 
                    type="text" 
                    required
                    value={formState.name}
                    onChange={(e) => setFormState({...formState, name: e.target.value})}
                    className="w-full bg-gray-50 dark:bg-white/5 border border-gray-200 dark:border-white/10 rounded-xl px-4 py-3 text-gray-900 dark:text-white outline-none focus:border-gold-500 transition-all"
                    placeholder="Ion Popescu"
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-xs font-bold text-gray-500 uppercase tracking-wider">Telefon</label>
                  <input 
                    type="tel" 
                    required
                    value={formState.phone}
                    onChange={(e) => setFormState({...formState, phone: e.target.value})}
                    className="w-full bg-gray-50 dark:bg-white/5 border border-gray-200 dark:border-white/10 rounded-xl px-4 py-3 text-gray-900 dark:text-white outline-none focus:border-gold-500 transition-all"
                    placeholder="07xx xxx xxx"
                  />
                </div>
              </div>

              <div className="space-y-2">
                <label className="text-xs font-bold text-gray-500 uppercase tracking-wider">Email</label>
                <input 
                  type="email" 
                  required
                  value={formState.email}
                  onChange={(e) => setFormState({...formState, email: e.target.value})}
                  className="w-full bg-gray-50 dark:bg-white/5 border border-gray-200 dark:border-white/10 rounded-xl px-4 py-3 text-gray-900 dark:text-white outline-none focus:border-gold-500 transition-all"
                  placeholder="email@exemplu.ro"
                />
              </div>

              <div className="space-y-2">
                <label className="text-xs font-bold text-gray-500 uppercase tracking-wider">Mesaj</label>
                <textarea 
                  required
                  rows={4}
                  value={formState.message}
                  onChange={(e) => setFormState({...formState, message: e.target.value})}
                  className="w-full bg-gray-50 dark:bg-white/5 border border-gray-200 dark:border-white/10 rounded-xl px-4 py-3 text-gray-900 dark:text-white outline-none focus:border-gold-500 transition-all resize-none"
                  placeholder="Sunt interesat de..."
                />
              </div>

              <button 
                type="submit" 
                disabled={isSubmitting}
                className="w-full bg-gold-500 hover:bg-gold-600 text-black font-bold py-4 rounded-xl transition-all shadow-lg hover:shadow-gold-500/20 flex items-center justify-center gap-2 disabled:opacity-70 disabled:cursor-not-allowed"
              >
                {isSubmitting ? 'Se trimite...' : (
                  <>
                    Trimite Mesajul <Send size={18} />
                  </>
                )}
              </button>
            </form>
          </div>
        </div>

        {/* Contact Info Side */}
        <div className="lg:col-span-5 space-y-6 animate-fade-in-right">
          
          {/* Quick Contact Card */}
          <div className="glass-panel p-8 rounded-3xl bg-white dark:bg-[#121212] border border-gray-200 dark:border-white/10">
            <h3 className="text-xl font-display font-bold text-gray-900 dark:text-white mb-6">Informații Rapide</h3>
            
            <div className="space-y-6">
              <a href="tel:+40740513713" className="flex items-center gap-4 group">
                <div className="w-12 h-12 rounded-full bg-gold-500/10 flex items-center justify-center text-gold-500 group-hover:bg-gold-500 group-hover:text-black transition-all">
                  <Phone size={20} />
                </div>
                <div>
                  <p className="text-xs text-gray-500 uppercase font-bold">Telefon Vânzări</p>
                  <p className="text-lg font-bold text-gray-900 dark:text-white">0740 513 713</p>
                </div>
              </a>

              <a href="mailto:autoparcrolcris@gmail.com" className="flex items-center gap-4 group">
                <div className="w-12 h-12 rounded-full bg-gold-500/10 flex items-center justify-center text-gold-500 group-hover:bg-gold-500 group-hover:text-black transition-all">
                  <Mail size={20} />
                </div>
                <div>
                  <p className="text-xs text-gray-500 uppercase font-bold">Email</p>
                  <p className="text-lg font-bold text-gray-900 dark:text-white">autoparcrolcris@gmail.com</p>
                </div>
              </a>

              <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-full bg-gold-500/10 flex items-center justify-center text-gold-500">
                  <Clock size={20} />
                </div>
                <div>
                  <p className="text-xs text-gray-500 uppercase font-bold">Program</p>
                  <p className="text-sm text-gray-900 dark:text-white font-medium">Luni - Vineri: 09:00 - 18:00</p>
                  <p className="text-sm text-gray-900 dark:text-white font-medium">Sâmbătă: 09:00 - 14:00</p>
                </div>
              </div>
            </div>

            <div className="mt-8 pt-8 border-t border-gray-200 dark:border-white/10">
              <a 
                href="https://wa.me/40740513713" 
                target="_blank" 
                rel="noreferrer" 
                className="flex items-center justify-center gap-3 bg-[#25D366] hover:bg-[#20bd5a] text-white py-3 rounded-xl font-bold transition-all shadow-lg hover:scale-[1.02]"
              >
                <MessageSquare size={20} />
                Chat pe WhatsApp
              </a>
            </div>
          </div>

          {/* Locations List (Simple) */}
          <div className="glass-panel p-8 rounded-3xl bg-gray-900 text-white relative overflow-hidden group">
            <div className="absolute inset-0 opacity-20 group-hover:opacity-30 transition-opacity">
               <img src="https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?q=80&w=1000&auto=format&fit=crop" className="w-full h-full object-cover" alt="Map bg" />
            </div>
            <div className="relative z-10">
              <h3 className="text-xl font-display font-bold mb-4 flex items-center gap-2">
                <MapPin className="text-gold-500" /> Locațiile Noastre
              </h3>
              <div className="space-y-4">
                {locations.map((loc, i) => (
                  <div key={i} className="flex items-start gap-3 border-b border-white/10 pb-3 last:border-0 last:pb-0">
                    <div className="mt-1 w-2 h-2 rounded-full bg-gold-500" />
                    <div>
                      <p className="font-bold text-gold-500">{loc.city}</p>
                      <p className="text-sm text-gray-300">{loc.addr}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

        </div>
      </div>

      {/* Visual Locations Section (Functional Maps) */}
      <section className="max-w-7xl mx-auto mb-16">
        <h2 className="text-3xl font-display font-bold text-gray-900 dark:text-white mb-12 text-center">Harta Locațiilor</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {locations.map((loc, i) => (
            <div key={i} className="flex flex-col bg-white dark:bg-[#121212] rounded-2xl overflow-hidden shadow-xl border border-gray-200 dark:border-white/10 group hover:border-gold-500/50 transition-all">
              {/* Map Container */}
              <div className="h-72 w-full bg-gray-200 dark:bg-gray-800 relative">
                 <iframe
                  width="100%"
                  height="100%"
                  title={`Map ${loc.city}`}
                  src={`https://maps.google.com/maps?q=${loc.mapQuery}&t=&z=15&ie=UTF8&iwloc=&output=embed`}
                  style={{ border: 0 }}
                  loading="lazy"
                  className="absolute inset-0 filter grayscale-[50%] hover:grayscale-0 transition-all duration-500"
                  allowFullScreen
                ></iframe>
              </div>
              
              {/* Info Container */}
              <div className="p-6">
                <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-2 flex items-center gap-2">
                  <MapPin className="text-gold-500" size={20} />
                  {loc.city}
                </h3>
                <p className="text-gray-500 dark:text-gray-400 text-sm mb-6">{loc.addr}</p>
                <a 
                  href={`https://www.google.com/maps?q=${loc.mapQuery}`} 
                  target="_blank" 
                  rel="noreferrer" 
                  className="w-full inline-flex items-center justify-center gap-2 bg-gray-100 dark:bg-white/5 hover:bg-gold-500 hover:text-black text-gray-900 dark:text-white py-3 rounded-lg font-bold transition-all"
                >
                  Indicații de orientare <ExternalLink size={16} />
                </a>
              </div>
            </div>
          ))}
        </div>
      </section>

    </div>
  );
};

export default Contact;
